name: Deploy to GitHub

on:
  schedule:
    - cron: '*/5 * * * *' # Her 5 dakikada bir deploy işlemini gerçekleştirir

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        node-version: 16

    - name: Install dependencies
      run: pip install ftputil

    - name: Download files from FTP
      run: |
        import ftputil
        with ftputil.FTPHost('64.226.120.146', 'hafsa1319', 'meleK1319') as host:
          host.download_if_newer('/httpdocs', 'httpdocs')

    - name: Commit and push changes
      run: |
        git config --global user.email "info@hafsa.de"
        git config --global user.name "hafsa1319"
        git add .
        git commit -m "Update files from FTP"
        git push
